cd /etc/rc.d/
./S99http_client_detect off
rm S99http_client_detect
./S99ad_filter off
rm S99ad_filter
./S98rule_mgr stop
rm S98rule_mgr
./S99http_status_stat off
rm S99http_status_stat
./K09statisticsservice stop
./K09statisticsservice disable
rm K09statisticsservice 
rm S99statisticsservice
./S21sysapihttpd stop
./S21sysapihttpd disable
rm S21sysapihttpd
/S49messagingagent.sh stop
./S49messagingagent.sh disable
rm ./S49messagingagent.sh 
